version: '3.1'

services:

  db:
    image: mysql
    volumes:
      - my-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USERMYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
            
volumes:
  my-db: